---
title: Reverts changes
description: Reverts changes from past versions
privilege: TrustedInstaller
onUpgrade: true
actions:
  - !writeStatus: { status: "Reverting old changes" }
  - !powerShell:
    command: '& (Join-Path $env:windir "AtlasModules\Scripts\Helpers\Fix-Store.ps1") -Silent'
    weight: 2
    wait: true
    onUpgrade: true
