---
title: Disable Mitigations
description: Disables mitigations in Windows dependent on the user's options
option: 'mitigations-disable'
actions:
  - !powerShell:
    command: '& (Join-Path $env:windir ''AtlasDesktop\7. Security\Mitigations\Disable All Mitigations.ps1'') -Silent'
    exeDir: true
    wait: true
    runas: currentUserElevated
