---
title: Set File Associations
description: Sets file associations for the user-selected web browser and other apps
actions:
  - !powerShell:
    command: '.\AtlasModules\Scripts\Set-BrowserFileAssociations.ps1'
    exeDir: true
    wait: true
    option: '!uninstall-edge'
  - !powerShell:
    command: '.\AtlasModules\Scripts\Set-BrowserFileAssociations.ps1 -Browser "Brave"'
    exeDir: true
    wait: true
    option: 'browser-brave'
  - !powerShell:
    command: '.\AtlasModules\Scripts\Set-BrowserFileAssociations.ps1 -Browser "LibreWolf"'
    exeDir: true
    wait: true
    option: 'browser-librewolf'
  - !powerShell:
    command: '.\AtlasModules\Scripts\Set-BrowserFileAssociations.ps1 -Browser "Firefox"'
    exeDir: true
    wait: true
    option: 'browser-firefox'
  - !powerShell:
    command: '.\AtlasModules\Scripts\Set-BrowserFileAssociations.ps1 -Browser "Google Chrome"'
    exeDir: true
    wait: true
    option: 'browser-chrome'
