readme:
  - changed-files:
    - any-glob-to-any-file: '**/README.md'

actions:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/labeler.yml'

# Playbook

playbook:
  - changed-files:
    - any-glob-to-any-file: 'src/playbook/**/*'

appx:
  - changed-files:
    - any-glob-to-any-file: 'src/playbook/Configuration/atlas/appx.yml'

components:
  - changed-files:
    - any-glob-to-any-file: 'src/playbook/Configuration/atlas/components.yml'

services:
  - changed-files:
    - any-glob-to-any-file: 'src/playbook/Configuration/atlas/services.yml'

tweaks:
  - changed-files:
    - any-glob-to-any-file:
      - 'src/playbook/Configuration/tweaks.yml'
      - 'src/playbook/Configuration/tweaks/**/*'

desktop folder:
  - changed-files:
    - any-glob-to-any-file: 'src/playbook/Executables/AtlasDesktop/**/*'
