---
title: Disable Click To Do
description: Disables the Click To Do AI feature
builds: [ '>=22000' ]
actions:
  - !powerShell:
    command: '& (Join-Path $env:windir ''AtlasDesktop\3. General Configuration\AI Features\Click To Do\Disable Click To Do (default).ps1'') -Silent'
    exeDir: true
    wait: true
    runas: currentUserElevated

