[Theme]
DisplayName=Atlas v0.5.x Dark
ThemeId={5F8F7C9B-455A-4BDC-BE7F-1B70AE765E97}

[Control Panel\Desktop]
Wallpaper=%windir%\AtlasModules\Wallpapers\atlas-v0.5.x-dark.png
Pattern=
MultimonBackgrounds=0
PicturePosition=4
WindowsSpotlight=0

[Control Panel\Cursors]
AppStarting=%SystemRoot%\cursors\wait_r.cur
Arrow=%SystemRoot%\cursors\arrow_r.cur
Hand=
Help=%SystemRoot%\cursors\help_r.cur
No=%SystemRoot%\cursors\no_r.cur
NWPen=%SystemRoot%\cursors\pen_r.cur
SizeAll=%SystemRoot%\cursors\move_r.cur
SizeNESW=%SystemRoot%\cursors\size1_r.cur
SizeNS=%SystemRoot%\cursors\size4_r.cur
SizeNWSE=%SystemRoot%\cursors\size2_r.cur
SizeWE=%SystemRoot%\cursors\size3_r.cur
UpArrow=%SystemRoot%\cursors\up_r.cur
Wait=%SystemRoot%\cursors\busy_r.cur
DefaultValue=Windows Black
Crosshair=%SystemRoot%\cursors\cross_r.cur
IBeam=%SystemRoot%\cursors\beam_r.cur
Pin=%SystemRoot%\cursors\pin_r.cur
Person=%SystemRoot%\cursors\person_r.cur

[Sounds]
SchemeName=No Sounds

[VisualStyles]
Path=%windir%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XC44A51A8
SystemMode=Dark
AppMode=Dark
VisualStyleVersion=10

[MasterThemeSelector]
MTSM=RJSPBS
