[Theme]
DisplayName=Atlas Solid
ThemeId={1545A5F7-3E0C-4670-8A21-99FDEEA37AA5}

[Control Panel\Desktop]
Wallpaper=%windir%\AtlasModules\Wallpapers\atlas-solid.png
Pattern=
MultimonBackgrounds=0
PicturePosition=4
WindowsSpotlight=0

[Control Panel\Cursors]
AppStarting=%windir%\cursors\wait_r.cur
Arrow=%windir%\cursors\arrow_r.cur
Hand=
Help=%windir%\cursors\help_r.cur
No=%windir%\cursors\no_r.cur
NWPen=%windir%\cursors\pen_r.cur
SizeAll=%windir%\cursors\move_r.cur
SizeNESW=%windir%\cursors\size1_r.cur
SizeNS=%windir%\cursors\size4_r.cur
SizeNWSE=%windir%\cursors\size2_r.cur
SizeWE=%windir%\cursors\size3_r.cur
UpArrow=%windir%\cursors\up_r.cur
Wait=%windir%\cursors\busy_r.cur
DefaultValue=Windows Black
Crosshair=%windir%\cursors\cross_r.cur
IBeam=%windir%\cursors\beam_r.cur
Pin=%windir%\cursors\pin_r.cur
Person=%windir%\cursors\person_r.cur

[Sounds]
SchemeName=No Sounds

[VisualStyles]
Path=%SystemRoot%\resources\themes\Aero\Aero.msstyles
ColorStyle=NormalColor
Size=NormalSize
AutoColorization=0
ColorizationColor=0XC42D7D9A
SystemMode=Dark
AppMode=Dark
VisualStyleVersion=10

[MasterThemeSelector]
MTSM=RJSPBS