---
title: Applies Atlas' Network Settings
description: Applies Atlas' optimised network settings
actions:
  - !powerShell:
    command: '& (Join-Path $env:windir ''AtlasDesktop\9. Troubleshooting\Network\Reset Network to Atlas Default.ps1'') -Silent'
    exeDir: true
    wait: true
    runas: currentUserElevated
