---
title: Disable Teredo Tunneling
description: Disables Teredo IPv6 tunneling, which can add latency and is an unnecessary attack surface for most home users
actions:
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters'
    value: 'DisabledComponents'
    data: '1'
    type: REG_DWORD
  - !run: {exe: 'netsh', args: 'interface teredo set state disabled'}
